---
- hosts: R1
  gather_facts: false
  tasks:
  - name: Configure lo0 interface
    ios_config:
      parents: interface lo0
      lines:
        - ip address 192.168.10.1 255.255.255.0
        - no shutdown

  - name: Configure lo1 interface
    ios_config:
      parents: interface lo1
      lines:
        - ip address 192.168.20.1 255.255.255.0
        - no shutdown

  - name: Configure OSPF
    ios_config:
      parents: router ospf 1
      lines:
        - network 172.168.1.0 0.0.0.31 area 1
        - network 192.168.2.0 0.0.0.3 area 1
        - network 192.168.10.1 0.0.0.255 area 1
        - network 192.168.20.1 0.0.0.255 area 1
      replace: block
...