---
- name: Configure OSPF and Interface on R1
  hosts: R1
  gather_facts: no

  tasks:
  - name: Configure loopback interfaces
    ios_config:
      lines:
        - ip address {{ item.ip }}
        - no shutdown
      parents: interface {{ item.name }}
      replace: block
    with_items:
      - { name: 'lo0', ip: '192.168.10.1 255.255.255.0' }
      - { name: 'lo1', ip: '192.168.20.1 255.255.255.0' }

  - name: Configure OSPF
    ios_config:
      lines:
        - network 172.168.1.0 0.0.0.31 area 1
        - network 192.168.2.0 0.0.0.3 area 1
        - network 192.168.10.1 0.0.0.255 area 1
        - network 192.168.20.1 0.0.0.255 area 1
      parents: router ospf 1
      replace: block
...