---
- name: Configure Network
  hosts: R4
  gather_facts: False
  tasks:
    - name: Configure interface lo0
      ios_config:
        lines:
          - ip address 192.168.70.1 255.255.255.0
          - no shutdown
        parents: interface lo0
        replace: block

    - name: Configure interface lo1
      ios_config:
        lines:
          - ip address 192.168.80.1 255.255.255.0
          - no shutdown
        parents: interface lo1
        replace: block

    - name: Configure OSPF
      ios_config:
        parents:
          - router ospf 1
        lines:
          - network 192.168.6.0 0.0.0.3 area 100
          - network 192.168.70.1 0.0.0.255 area 100
          - network 192.168.80.1 0.0.0.255 area 100
        replace: block
...