---
- name: Network Automation Playbook
  hosts: R1
  gather_facts: false
  tasks:
  
  - name: Configuring OSPF routing protocol
    ios_config:
      lines:
        - router ospf 1
        - network 172.168.1.0 0.0.0.31 area 1
        - network 192.168.2.0 0.0.0.3 area 1
        - network 192.168.10.1 0.0.0.255 area 1
        - network 192.168.20.1 0.0.0.255 area 1
      replace: block
      
  - name: Configuring Loopback Interface lo0
    ios_config:
      lines:
        - ip address 192.168.10.1 255.255.255.0
        - no shutdown
      parents: interface lo0
      replace: block

  - name: Configuring Loopback Interface lo1
    ios_config:
      lines:
        - ip address 192.168.20.1 255.255.255.0
        - no shutdown
      parents: interface lo1
      replace: block
...