---
- hosts: R4
  gather_facts: no
  tasks:
    - name: configure loopback interfaces
      ios_config:
        parents: interface {{ item.name }}
        lines:
          - ip address {{ item.ip }}
          - no shutdown
        replace: block
      loop:
        - { name: 'lo0', ip: '192.168.70.1 255.255.255.0' }
        - { name: 'lo1', ip: '192.168.80.1 255.255.255.0' }

    - name: setup OSPF
      ios_config:
        parents: router ospf 1
        lines:
          - network {{ item.network }} area 100
        replace: block
      loop:
        - { network: '192.168.6.0 0.0.0.3' }
        - { network: '192.168.70.1 0.0.0.255' }
        - { network: '192.168.80.1 0.0.0.255' }
...