---
- hosts: R3
  gather_facts: no
  tasks:
    - name: Configure interface lo0
      ios_config:
        lines:
          - ip address 192.168.50.1 255.255.255.0
          - no shutdown
        parents: interface lo0

    - name: Configure interface lo1
      ios_config:
        lines:
          - ip address 192.168.60.1 255.255.255.0
          - no shutdown
        parents: interface lo1

    - name: Configure EIGRP
      ios_config:
        lines:
          - network 192.168.4.0 0.0.0.3
          - network 192.168.50.1 0.0.0.255         
        parents: router eigrp 10

    - name: Configure OSPF
      ios_config:
        lines:
          - network 192.168.6.0 0.0.0.3 area 100
          - network 192.168.60.1 0.0.0.255 area 100
        parents: router ospf 1

    - name: Redistribute OSPF into EIGRP
      ios_config:
        lines:
          - redistribute ospf 1 metric 1000 33 255 1 1500
        replace: block
        parents: router eigrp 10

    - name: Redistribute EIGRP into OSPF
      ios_config:
        lines:
          - redistribute eigrp 10 subnets
        replace: block
        parents: router ospf 1    
...