---
- hosts: R4
  gather_facts: no
  tasks:
  - name: Configure lo0 interface
    ios_config:
      lines:
       - ip address 192.168.70.1 255.255.255.0
       - no shutdown
      parents: interface lo0
      replace: block
  - name: Configure lo1 interface
    ios_config:
      lines:
       - ip address 192.168.80.1 255.255.255.0
       - no shutdown
      parents: interface lo1
      replace: block
  - name: Configure OSPF
    ios_config:
      lines:
       - network 192.168.6.0 0.0.0.3 area 100
       - network 192.168.70.1 0.0.0.255 area 100
       - network 192.168.80.1 0.0.0.255 area 100
      parents: router ospf 1
      replace: block
...