---
- name: Configure interfaces and OSPF on R4
  hosts: R4
  gather_facts: no
  tasks:
  - name: Configure lo0 interface
    ios_config:
      parents: interface lo0
      lines:
      - ip address 192.168.70.1 255.255.255.0
      - no shutdown
      replace: block

  - name: Configure lo1 interface
    ios_config:
      parents: interface lo1
      lines:
      - ip address 192.168.80.1 255.255.255.0
      - no shutdown
      replace: block

  - name: Configure OSPF
    ios_config:
      parents: router ospf 1
      lines:
      - network 192.168.6.0 0.0.0.3 area 100
      - network 192.168.70.1 0.0.0.255 area 100
      - network 192.168.80.1 0.0.0.255 area 100
      replace: block
...