---
- name: Playbook for Network Automation
  hosts: R4
  gather_facts: no
  tasks:

  - name: Configuring lo0 interface
    ios_config:
      lines:
      - interface lo0
      - ip address 192.168.70.1 255.255.255.0
      - no shutdown
      replace: block

  - name: Configuring lo1 interface
    ios_config:
      lines:
      - interface lo1
      - ip address 192.168.80.1 255.255.255.0
      - no shutdown
      replace: block

  - name: Configuring OSPF routing protocol
    ios_config:
      lines:
      - router ospf 1
      - network 192.168.6.0 0.0.0.3 area 100
      - network 192.168.70.1 0.0.0.255 area 100
      - network 192.168.80.1 0.0.0.255 area 100
      replace: block
      parents: router ospf 1 
...